### ISSUE TITLE
Getting segmentation fault at the end

### ISSUE THREAD

**Issue by madhur** [jrk/credis#2]
> [root@redismaster credis]# ./credis-test
> Testing a number of credis functions. To perform a simplistic set-command
> benchmark, run: `./credis-test <num>' where <num> is the number
> of set-commands to send.
> 
> 
> 
> ************* misc info ************************************
> ping returned: 0
> lastsave returned: 1481682199
> info returned -97
> >redis_version:
> >uptime_in_seconds: 428880367
> >uptime_in_days: 32764
> >connected_clients: 32764
> >connected_slaves: 0
> >used_memory: 1
> >changes_since_last_save: 0
> >bgsave_in_progress: 428880408
> >last_save_time: 4195949
> >total_connections_received: 194
> >total_commands_processed: 140720737366510
> >role: 1
> 
> 
> ************* get/set ************************************
> set kalle=kula returned: 0
> get kalle returned: 4
> getset kalle=buhu returned: 4
> get kalle returned: 4
> del kalle returned: 0
> get kalle returned: (null)
> get adam returned: 3
> get bertil returned: 7
> get caesar returned: 4
> mget returned: 5
>   0: (null)
>   1: 3
>   2: (null)
>   3: 7
>   4: (null)
> keys returned: -97
> 
> 
> ************* sets ************************************
> sadd returned: -97
> sismember returned: -97
> sadd returned: -97
> srem returned: -97
> sismember returned: -97
> srem returned: -97
> 
> 
> ************* lists ************************************
> length of list: -95
> del returned: -97
> length of list: -97
> rpush returned: -97
> rpush returned: -97
> rpush returned: -97
> lpush returned: -97
> lrange (0, 2) returned: -97
> lrange (0, -1) returned: -97
> rpush returned: -97
> Segmentation fault

**Comment by jrk** [comment]
Thanks for the report, but this repo is just a (now very stale) GitHub mirror of another project: https://code.google.com/archive/p/credis/

I'm going to delete the repo to avoid confusion.
